In [ ]:
#Install required packages
!pip install lshkrepresentatives numpy scikit-learn pandas kmodes networkx termcolor

In [2]:
import numpy as np
from LSHkRepresentatives.LSHkRepresentatives import CategoricalDatasetNormalization,LSHkRepresentatives

In [9]:
#Example of non normalized categorical dataset (there are strings, numbers, and nan values)
X = np.array([['a',np.nan,45],
              [0,1,1],
              ['g',0,0],
              [1,0,1],
              ['g',2,2],
              [2,3,2],
              ['fg',3,2]])

In [4]:
#Normalize it by CategoricalDatasetNormalization instance
normalizer = CategoricalDatasetNormalization(X)
X_categorical = normalizer.Normalize(X)
X_categorical

array([[3, 4, 3],
       [0, 1, 1],
       [5, 0, 0],
       [1, 0, 1],
       [5, 2, 2],
       [2, 3, 2],
       [4, 3, 2]])

In [5]:
#Do clustering 
kreps = LSHkRepresentatives(n_clusters=2,n_init=5) 
kreps.fit(X_categorical)

SKIP LOADING distMatrix because IS_LOAD_AUTO=False or dbname=None; If you cluster a dataset multiple times, make sure to include the 'dbname' parameter during initialization to cache the distance matrix of the dataset. Calculating distance matrix can take a lot of time with high categirical values dataset.
Generating disMatrix for DILCA
Saving DILCA to: saved_dist_matrices/json/DILCA_None.json
Generating LSH hash table:   hbits: 2(4)  k 1  d 3  n= 7
LSH time: 0.008334099999046884 Score:  11.333333333333334  Time: 0.00031906000076560305


array([0, 0, 0, 0, 1, 1, 1], dtype=uint16)

In [7]:
#Normlize test/query dataset using the trained normalizer
x2 = np.array([['a',2,0],[2,2,2]])
x2_normalized = normalizer.Normalize(x2)
x2_normalized

array([[3, 2, 0],
       [2, 2, 2]])

In [8]:
#Predic the normalized test/query 
labels_test = kreps.predict(x2_normalized)
labels_test

array([0, 1], dtype=int64)